### PR TITLE
build-env: Support arm64

### PR DESCRIPTION
**Pull request by samip5**

### CODE REVIEW

**Comment by vktr** [comment]
I realize now - is it possible to do this in two separate PR's? We'd need to adjust the stripping of the binary, but is that all that's left? I'll see if I can pull this and push a new version of the build-env image, then maybe we can try to get the main PR going. What do you think?

**Comment by samip5** [comment]
@vktr I do have two separate PR's open for this?

**Comment by vktr** [comment]
Yeah sorry for the confusion - I meant that it might not be possible due to how things are set up in Porla 😅 But I can live with a broken CI until things are sorted as well!

**Comment by samip5** [comment]
> Yeah sorry for the confusion - I meant that it might not be possible due to how things are set up in Porla 😅 But I can live with a broken CI until things are sorted as well!

Please try out the dev container I pushed and see for yourself that I was able to build the multi-arch container without really much issue.

It's at `registry.samipsolutions.fi/library/porla:dev` and build-env container is at `registry.samipsolutions.fi/library/porla-build-env:20230605`.

**Comment by samip5** [comment]
Regarding the CI, I think the other PR does have most of the required changes made to the workflows, but I'm not sure how those binary copying and uploading parts should be done.

**Comment by vktr** [comment]
This is awesome stuff! Seems like this last commit will make it green - then I'll merge it 😄 What would be left to do after this PR is merged? Mostly GH Actions changes, right?

**Comment by samip5** [comment]
Yes, mostly GH action things after getting this merged and the new multi-arch container created & pushed (which doesn't seem to be done by CI at all).

**Comment by vktr** [comment]
> Regarding the CI, I think the other PR does have most of the required changes made to the workflows, but I'm not sure how those binary copying and uploading parts should be done.

Hm, maybe it's possible to create a container and specify an architecture? All we want to do is capture the built binary file from inside the container.

> Yes, mostly GH action things after getting this merged and the new multi-arch container created & pushed (which doesn't seem to be done by CI at all).

Yeah, the build env is something I've manually been pushing when vcpkg updates have arrived. Maybe we should automate that as well in the future but I'll build it manually and push a new version when it's been merged!

**Comment by samip5** [comment]
> Yeah, the build env is something I've manually been pushing when vcpkg updates have arrived. Maybe we should automate that as well in the future but I'll build it manually and push a new version when it's been merged!

You need to have docker buildx enabled.

For Kubernetes:
```
# Create the builder itself for amd64
docker buildx create --bootstrap --name kube --driver=kubernetes --platform=linux/amd64 --node builder-amd64 --driver-opt=namespace=ci,nodeselector="kubernetes.io/arch=amd64"
# Bootstrap an arm64 builder too
docker buildx create --append --bootstrap --name kube --driver=kubernetes --platform=linux/arm64 --node builder-arm64 --driver-opt=namespace=ci,nodeselector="kubernetes.io/arch=arm64"
# Use the builder
docker buildx use kube
# Actually build it
docker buildx build  . --platform linux/arm64,linux/amd64 --push -t registry.samipsolutions.fi/library/porla-dev-env:<timestamp-tag>
```

Those buildx builders should be doable in qemu too: https://docs.docker.com/build/guide/multi-platform/#build-using-emulation


> > Regarding the CI, I think the other PR does have most of the required changes made to the workflows, but I'm not sure how those binary copying and uploading parts should be done.
> 
> Hm, maybe it's possible to create a container and specify an architecture? All we want to do is capture the built binary file from inside the container.
> 
> >

Probably possible in matrix build or some other way to know which arch container it is for it to know which filename to try to get and to name it correctly in artifacts.

**Comment by vktr** [comment]
Thanks for the instructions! Do you know it works with minikube or microk8s?

**Comment by samip5** [comment]
> Thanks for the instructions! Do you know it works with minikube or microk8s?

I think it might not, as that expects there to be a node which matches those architecture labels which might not be the case for arm64 at least. It should be possible to do both on a single kubernetes builder though.

Basically just this should be the difference:
```
docker buildx create --bootstrap --name kube --driver=kubernetes --platform=linux/amd64,linux/arm64
```

**Comment by vktr** [comment]
I'll check tomorrow when I'm at a real computer again 👍

**Pull request merged**
